/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Learn_With_Web_Classes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;

/**
 *
 * @author PAUL
 */
public class Forget extends javax.swing.JFrame {
    private void reset()
    {
    txtusr.setText("");    
    txtans.setText("");
    list.setSelectedIndex(0);
    
    }
    private void closeMe()
    {
    WindowEvent evt=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(evt);
    }
    Dimension ssize=Toolkit.getDefaultToolkit().getScreenSize();
    public Forget() {
        initComponents();
      this.setLocation((int)ssize.getWidth()/2-this.getWidth()/2,(int)ssize.getHeight()/2-this.getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        lname = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtans = new javax.swing.JTextField();
        subbmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 250));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Question", "Your Favourate City", "Your Favourate Teacher", "Nick Name you Like", "Best Book you Like", "Best Mobile Company you like" }));
        getContentPane().add(list);
        list.setBounds(250, 120, 190, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Answer*");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 160, 90, 20);

        line.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        getContentPane().add(line);
        line.setBounds(0, 50, 510, 2);

        lname.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lname.setText("Forget");
        getContentPane().add(lname);
        lname.setBounds(190, 0, 130, 50);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Learn_With_Web_Classes/images/back_areo.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(460, 10, 40, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 80, 74, 20);
        getContentPane().add(txtusr);
        txtusr.setBounds(250, 80, 190, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Security Question*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 120, 104, 16);
        getContentPane().add(txtans);
        txtans.setBounds(250, 160, 190, 25);

        subbmit.setText("Submit");
        subbmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbmitActionPerformed(evt);
            }
        });
        getContentPane().add(subbmit);
        subbmit.setBounds(190, 200, 80, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Learn_With_Web_Classes/images/back_forget.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subbmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbmitActionPerformed
       if(txtusr.getText().isEmpty() || txtans.getText().isEmpty() || list.getSelectedIndex()==0)
           DialogBox.okDialogError("Fields Can't be Empty");
       else
       {
        Connect c=new Connect();
        Connection conn=c.connectTo();
        int log=0;
        try
        {
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("Select * from mydb.logins");
            while(rs.next())
            {
                if(rs.getString("username").equalsIgnoreCase(txtusr.getText()) && rs.getString("question").equalsIgnoreCase(String.valueOf(list.getSelectedItem())) && rs.getString("answer").equalsIgnoreCase(txtans.getText()))
                {
                   DialogBox.okDialog("Password :-"+rs.getString("password")); 
                    reset();
                    log=1;
                    break;
                }
            }
            st.close();
            rs.close();
            conn.close();            
            if(log==0)
            {
                DialogBox.okDialogError("Invalid username or Security_Question");
            }
        }catch(SQLException ex){DialogBox.okDialogError("SQL QUERY ERROR");}}
    }//GEN-LAST:event_subbmitActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        closeMe();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel line;
    private javax.swing.JComboBox<String> list;
    private javax.swing.JLabel lname;
    private javax.swing.JButton subbmit;
    private javax.swing.JTextField txtans;
    private javax.swing.JTextField txtusr;
    // End of variables declaration//GEN-END:variables
}
